# Generated by Django 4.1.1 on 2022-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affliates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=45, null=True)),
                ('phonenumber', models.CharField(max_length=45, null=True)),
                ('emailaddress', models.CharField(max_length=45, null=True, unique=True)),
                ('address', models.CharField(default='', max_length=250)),
                ('fullname_kin', models.CharField(max_length=45, null=True)),
                ('phonenumber_kin', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45, null=True)),
                ('lastname', models.CharField(max_length=45, null=True)),
                ('emailaddress', models.CharField(max_length=45, null=True, unique=True)),
                ('companyname', models.CharField(default='', max_length=250)),
                ('country', models.CharField(default='', max_length=45, null=True)),
                ('phonenumber', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45, null=True)),
                ('lastname', models.CharField(max_length=45, null=True)),
                ('emailaddress', models.CharField(max_length=45, null=True, unique=True)),
                ('password', models.CharField(default='', max_length=45)),
                ('confirm_password', models.CharField(default='', max_length=45)),
                ('about_us', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=45, null=True)),
                ('phonenumber', models.CharField(max_length=45, null=True)),
                ('emailaddress', models.CharField(max_length=45, null=True, unique=True)),
                ('address', models.CharField(default='', max_length=250)),
                ('fullname_kin', models.CharField(max_length=45, null=True)),
                ('phonenumber_kin', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
