# Generated by Django 4.1.1 on 2022-09-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualinvestor',
            name='confirm_password',
        ),
    ]
