# Generated by Django 4.1.1 on 2022-09-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0002_remove_individualinvestor_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinvestor',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
