# Generated by Django 4.1.1 on 2022-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0003_alter_individualinvestor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliates',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='businessinvestor',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='password',
            field=models.CharField(default='', max_length=250),
        ),
    ]
