# Generated by Django 4.1.1 on 2022-09-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar_app', '0004_affliates_password_businessinvestor_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField()),
                ('sale_type', models.CharField(max_length=45, null=True)),
                ('sale_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('earning_duration', models.CharField(max_length=45, null=True)),
                ('affliateID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solar_app.affliates')),
            ],
        ),
    ]
